[tool.poetry]
name = "monday"
version = "0.1.0"
description = ""
authors = ["Giovanni <42703789+gbronca@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ruff = "^0.4.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
