from typing import Literal

COLUMNTYPE = Literal[
    "auto_number",
    "board_relation",
    "button",
    "checkbox",
    "color_picker",
    "country",
    "creation_log",
    "date",
    "dependency",
    "doc",
    "dropdown",
    "email",
    "file",
    "formula",
    "hour",
    "item_assignees",
    "item_id",
    "last_updated",
    "link",
    "location",
    "long_text",
    "mirror",
    "name",
    "numbers",
    "people",
    "phone",
    "progress",
    "rating",
    "status",
    "subtasks",
    "tags",
    "team",
    "text",
    "timeline",
    "time_tracking",
    "vote",
    "week",
    "world_clock",
    "unsupported",
]

OrderBy = Literal["created_at", "used_at"]

STATE = Literal["active", "all", "archived", "deleted"]
